- name: installing nginx
  hosts: all
  become: yes
  serial: 3
  #vars_files:
  #- /var/expense/credentials_nginx.yaml
  tasks:
  - name: installing nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes