- name: disabling nodejs 
  ansible.builtin.command: dnf module disable nodejs -y

- name: enabling nodejs
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: installing nodejs
  ansible.builtin.package: 
    name: "{{item}}"
    state: present
  loop:
  - nodejs
  - mysql

- name: create a user
  ansible.builtin.user:
    name: expense

- name: import the code from other role
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req.yaml


- name: installing dependencies
  tags:
  - deployment
  ansible.builtin.command: npm install
  args:
    chdir: /app

- name: copying backend service
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service

- name: installing mypysql module
  ansible.builtin.pip:
    name: "{{ item }}"
  loop:
    - PyMySQL
    - cryptography

- name: dumping mysql data
  community.mysql.mysql_db:
    login_user: root
    login_password: "{{ login_password }}"
    login_host: "{{ login_host }}"
    target: /app/schema/backend.sql
    name: all
    state: import

- name: starting the service
  tags: 
  - deployment
  ansible.builtin.service:
    name: backend
    state: restarted

